--
-- RagnarokOnline Settings File
-- Generated by RO OpenSetup, Version 3.2.1.651 ( http://ai4rei.net/p/opensetup )
--

-- Workaround for people with broken client folder
-- Note: The client removes this when it saves settings.
--
if OptionInfoList==nil then
	OptionInfoList = {}
end
if CmdOnOffList==nil then
	CmdOnOffList = {}
end
-- End of Workaround


-- Settings
--

OptionInfoList["Trilinear"] = 0
OptionInfoList["Bgm_Volume"] = 100
OptionInfoList["Effect_Volume"] = 100
OptionInfoList["MouseExclusive"] = 1
OptionInfoList["ISFULLSCREENMODE"] = 0
OptionInfoList["WIDTH"] = 1024
OptionInfoList["HEIGHT"] = 768
OptionInfoList["BITPERPIXEL"] = 32
OptionInfoList["DEVICECNT"] = 0
OptionInfoList["MODECNT"] = 0
OptionInfoList["SPRITEMODE"] = 2
OptionInfoList["TEXTUREMODE"] = 2
OptionInfoList["RENDERSYSTEM"] = 1
OptionInfoList["DX9DEVICEID"] = "{00000000-0000-0000-0000-000000000000}"
OptionInfoList["DX9DEVICENAME"] = ""
CmdOnOffList["/bgm"] = 1
CmdOnOffList["/sound"] = 1
CmdOnOffList["/notrade"] = 0
CmdOnOffList["/noshift"] = 0
CmdOnOffList["/noctrl"] = 1
CmdOnOffList["/skillfail"] = 1
CmdOnOffList["/notalkmsg"] = 0
CmdOnOffList["/notalkmsg2"] = 0
CmdOnOffList["/showname"] = 1
CmdOnOffList["/fog"] = 1
CmdOnOffList["/aura"] = 1
CmdOnOffList["/window"] = 0
CmdOnOffList["/miss"] = 1
CmdOnOffList["/effect"] = 1
CmdOnOffList["/shopping"] = 1
CmdOnOffList["/stateinfo"] = 1
CmdOnOffList["/loginout"] = 1
CmdOnOffList["/snap"] = 0
CmdOnOffList["/itemsnap"] = 0
CmdOnOffList["/skillsnap"] = 1
CmdOnOffList["/camera"] = 0
CmdOnOffList["/hoai"] = 0
CmdOnOffList["/merai"] = 0
CmdOnOffList["/lightmap"] = 1
CmdOnOffList["/monsterhp"] = 1
CmdOnOffList["/q1"] = 0
CmdOnOffList["/q2"] = 0
CmdOnOffList["/aura2"] = 0
CmdOnOffList["/btg"] = 1
CmdOnOffList["/cashshop"] = 1
CmdOnOffList["/goldpc"] = 1
CmdOnOffList["/roulette"] = 1
CmdOnOffList["/quake"] = 1
CmdOnOffList["/mable"] = 1
CmdOnOffList["/zoom"] = 0

-- Preserved client settings
--

